apiVersion: batch/v1
kind: Job
metadata:
  name: schedule-surveypush-test
spec:
  template:
    spec:
      containers:
      - name: schedule
        image: cloudbeta/restaurant-survey-push-service:0.1
        env:
        - name: TERM_DAY
          valueFrom:
            configMapKeyRef:
              name: config-survey-push
              key: term-day
        - name: TERM_HOUR
          valueFrom:
            configMapKeyRef:
              name: config-survey-push
              key: term-hour
      restartPolicy: Never
  backoffLimit: 4
