apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: survey-service
  labels:
    app: restaurant
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: restaurant
        tier: survey-service
    spec:
      containers:
        - image: cloudbeta/:0.1
          imagePullPolicy: Always
          name: survey-service
          ports:
            - containerPort: 8081
          env:
          - name: DB_HOSTINFO
            valueFrom:
              configMapKeyRef:
                name: db-book
                key: hostinfo
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mariadb-credential-book
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-credential-book
                key: password