apiVersion: v1
kind: Service
metadata:
  name: survey-service
  labels:
    app: restaurant
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
      nodePort: 32003
  selector:
    app: restaurant
    tier: survey-service