apiVersion: v1
kind: Service
metadata:
  name: push-service
  labels:
    app: restaurant
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32002
  selector:
    app: restaurant
    tier: push-service