apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: information-service
  labels:
    app: restaurant
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: restaurant
      tier: information-service
  template:
    metadata:
      labels:
        app: restaurant
        tier: information-service
    spec:
      containers:
        - image: lms8147/restaurant-information-service:0.5
          imagePullPolicy: Always
          name: information-service
          ports:
            - containerPort: 8080
          env:
          - name: DB_HOSTINFO
            valueFrom:
              configMapKeyRef:
                name: db-information
                key: hostinfo
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mariadb-credential-information
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-credential-information
                key: password
