apiVersion: v1
kind: Service
metadata:
  name: information-service
  labels:
    app: restaurant
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32010
  selector:
    app: restaurant
    tier: information-service